### ISSUE TITLE
DeltaTimeModifier

### ISSUE THREAD

**Issue by StephanMeijer** [N-BodyPhysicsSimulator/Main#52]
Write a modifier to change the delta-time. See #51

**Comment by StephanMeijer** [comment]
@highlow9 see last commit. Run `make test`. See that test failing and fix the test or fix the function.

**Comment by StephanMeijer** [comment]
Now working properly.

**Comment by highlow9** [comment]
Why was this closed? I thought it needed fixing?

**Comment by StephanMeijer** [comment]
It was closed because it was fixed.

**Comment by StephanMeijer** [comment]
Can you even read?

**Comment by highlow9** [comment]
No
